### ISSUE TITLE
Example class name is awful

### ISSUE THREAD

**Issue by IvanGuardado** [Kikobeats/whoops#3]
The class name you use in the examples doesn't add a good semantic to the code. Obviously everyone can assign the required module to any variable name, but you should set a right path to follow for people don't want to think about code semantics. 

So change this:
`var Errorifier = require('errorifier');`

To something more semantic like:
`var JSError = require('errorifier');`

(just an example)

**Comment by Kikobeats** [comment]
I'm thinking more in change the name of the library. Any suggestion?
